/** @deprecated - dont use */
export const materialDesignSysPalette = {
  background: '#F7F9FF',
  error: '#B00020',
  errorContainer: '#FFDAD6',
  inverseOnSurface: '#EEF1F6',
  inversePrimary: '#98CCF9',
  inverseSurface: '#2D3135',
  onBackground: '#181C20',
  onError: '#FFFFFF',
  onErrorContainer: '#410002',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#001E31',
  onPrimaryFixed: '#001E31',
  onPrimaryFixedVariant: '#054B71',
  onSecondary: '#FFFFFF',
  onSecondaryContainer: '#0D1D2A',
  onSecondaryFixed: '#0D1D2A',
  onSecondaryFixedVariant: '#394856',
  onSurface: '#181C20',
  onSurfaceVariant: '#42474E',
  onTertiary: '#FFFFFF',
  onTertiaryContainer: '#211534',
  onTertiaryFixed: '#211534',
  onTertiaryFixedVariant: '#4E4162',
  outline: '#72787E',
  outlineVariant: '#C2C7CE',
  primary: '#2B638B',
  primaryContainer: '#CCE5FF',
  primaryFixed: '#CCE5FF',
  primaryFixedDim: '#98CCF9',
  scrim: '#000000',
  secondary: '#51606F',
  secondaryContainer: '#D4E4F6',
  secondaryFixed: '#D4E4F6',
  secondaryFixedDim: '#B8C8D9',
  shadow: '#000000',
  surface: '#F7F9FF',
  surfaceBright: '#F7F9FF',
  surfaceContainer: '#EBEEF3',
  surfaceContainerHigh: '#E6E8EE',
  surfaceContainerHighest: '#E0E2E8',
  surfaceContainerLow: '#F1F4F9',
  surfaceContainerLowest: '#FFFFFF',
  surfaceDim: '#D7DADF',
  surfaceTint: '#2B638B',
  surfaceVariant: '#DEE3EB',
  tertiary: '#66587B',
  tertiaryContainer: '#ECDCFF',
  tertiaryFixed: '#ECDCFF',
  tertiaryFixedDim: '#D1BFE7'
};

export type M3SysPalette = Record<keyof typeof materialDesignSysPalette, string>;
export type M3SysPaletteKeys = keyof M3SysPalette;
